{{- if .Values.migration.enabled -}}
{{- $files := .Files.Glob "files/migrations/*.sql" }}
{{- if $files }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lima.fullname" . }}-migrations
  labels: {{ include "lima.labels" . | nindent 4 }}
binaryData:
  {{- range $path, $bytes := $files }}
  {{ base $path }}: {{ $bytes | toString | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}
