apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lima.fullname" . }}-web
  labels:
    {{- include "lima.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  replicas: {{ .Values.replicaCount.web }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "lima.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "lima.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: web
    spec:
      serviceAccountName: {{ include "lima.serviceAccountName" . }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: web
          image: {{ include "lima.image" (dict "global" .Values.global "image" .Values.images.web) }}
          imagePullPolicy: {{ .Values.images.web.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.web.port }}
              protocol: TCP
          env:
            - name: NODE_ENV
              value: "production"
            - name: API_BASE_URL
              value: {{ .Values.web.apiBaseURL | default (printf "http://%s-api:%d" (include "lima.fullname" .) (.Values.service.api.port | int)) | quote }}
            - name: NEXTAUTH_URL
              value: {{ .Values.web.nextauthURL | default "" | quote }}
            - name: NEXTAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "lima.secretName" . }}
                  key: jwtSecret
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 20
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources: {{ toYaml .Values.resources.web | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
      {{- with .Values.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
