{{- if .Values.autoscaling.api.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "lima.fullname" . }}-api
  labels:
    {{- include "lima.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "lima.fullname" . }}-api
  minReplicas: {{ .Values.autoscaling.api.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.api.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.api.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.api.targetMemoryUtilizationPercentage | default 80 }}
{{- end }}
---
{{- if .Values.autoscaling.worker.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "lima.fullname" . }}-worker
  labels:
    {{- include "lima.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "lima.fullname" . }}-worker
  minReplicas: {{ .Values.autoscaling.worker.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.worker.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.worker.targetCPUUtilizationPercentage }}
{{- end }}
---
{{- if .Values.autoscaling.web.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "lima.fullname" . }}-web
  labels:
    {{- include "lima.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "lima.fullname" . }}-web
  minReplicas: {{ .Values.autoscaling.web.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.web.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.web.targetCPUUtilizationPercentage }}
{{- end }}
