apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "lima.fullname" . }}-migrate-r{{ .Release.Revision }}
  labels: {{ include "lima.labels" . | nindent 4 }}
spec:
  backoffLimit: 5
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: "{{ .Values.migration.image.repository }}:{{ .Values.migration.image.tag }}"
          args:
            - "-path=/migrations"
            - "-database=$(DATABASE_URL)"
            - "up"
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "lima.fullname" . }}-secrets
                  key: databaseURL
          volumeMounts:
            - name: migrations
              mountPath: /migrations
      volumes:
        - name: migrations
          configMap:
            name: {{ include "lima.fullname" . }}-migrations
