{{- if .Values.podDisruptionBudget.api.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "lima.fullname" . }}-api
  labels:
    {{- include "lima.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  minAvailable: {{ .Values.podDisruptionBudget.api.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "lima.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: api
{{- end }}
---
{{- if .Values.podDisruptionBudget.worker.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "lima.fullname" . }}-worker
  labels:
    {{- include "lima.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  minAvailable: {{ .Values.podDisruptionBudget.worker.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "lima.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: worker
{{- end }}
---
{{- if .Values.podDisruptionBudget.web.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "lima.fullname" . }}-web
  labels:
    {{- include "lima.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  minAvailable: {{ .Values.podDisruptionBudget.web.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "lima.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: web
{{- end }}
