apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lima.secretName" . }}
  labels: {{ include "lima.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secrets.jwtSecret }}
  jwtSecret: {{ .Values.secrets.jwtSecret | quote }}
  {{- end }}
  {{- if .Values.secrets.databaseURL }}
  databaseURL: {{ .Values.secrets.databaseURL | quote }}
  {{- end }}
  {{- if .Values.secrets.redisURL }}
  redisURL: {{ .Values.secrets.redisURL | quote }}
  {{- end }}
  {{- if .Values.secrets.credentialsEncryptionKey }}
  credentialsEncryptionKey: {{ .Values.secrets.credentialsEncryptionKey | quote }}
  {{- end }}
  {{- if .Values.secrets.credentialsEncryptionKeyPrevious }}
  credentialsEncryptionKeyPrevious: {{ .Values.secrets.credentialsEncryptionKeyPrevious | quote }}
  {{- end }}
  {{- if .Values.secrets.oidcClientSecret }}
  oidcClientSecret: {{ .Values.secrets.oidcClientSecret | quote }}
  {{- end }}
  {{- range $k, $v := .Values.secrets.extra }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
