apiVersion: v1
kind: Service
metadata:
  name: {{ include "lima.fullname" . }}-web
  labels:
    {{- include "lima.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "lima.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: {{ .Values.service.web.port }}
      targetPort: http
      protocol: TCP
