apiVersion: v1
kind: Service
metadata:
  name: {{ include "lima.fullname" . }}-api
  labels:
    {{- include "lima.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "lima.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: {{ .Values.service.api.port }}
      targetPort: http
      protocol: TCP
